// src/app/layout.js
import './globals.css';
import ProSidebarWrapper                                                              from '@/components/ProSidebarWrapper/ProSidebarWrapper';
import { ClerkProvider, SignedIn, SignedOut, UserButton, SignInButton, SignUpButton } from '@clerk/nextjs';
import { ThemeProvider }                                                              from '../components/context/ThemeContext';
import { Geist, Geist_Mono }                                                          from 'next/font/google';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider>
          
          

            {/* Sidebar Wrapper */}
            <ProSidebarWrapper>
              {children}
            </ProSidebarWrapper>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
